In [1]:
import torch
import torch.nn as nn
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
block_size=8
batch_size=4

cuda


In [3]:
with open("wizard_of_oz.txt","r",encoding="utf-8") as f:
  text=f.read()
char=sorted(set(text))
print(char)
vocabulary_size=len(char)

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


In [4]:
string_to_int={ch:i for i,ch in enumerate(char)}
int_to_string={i:ch for i,ch in enumerate(char)}
encode=lambda s:[string_to_int[c] for c in s]
decode=lambda l: ''.join([int_to_string[i] for i in l])

data=torch.tensor(encode(text),dtype=torch.long)
print(data[:100])

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])


In [6]:
n=int(0.8*len(data))
train_data=data[:n]
val_data=data[n:]


def get_batch(split):
  data=train_data if split=='train' else val_data
  ix=torch.randint(len(data)-block_size, (batch_size,))
  x=torch.stack([data[i:i+block_size] for i in ix])
  y=torch.stack([data[i+1:i+block_size+1] for i in ix])
  # x,y=x.to(device), y.to(device)
  return x,y
x,y=get_batch('train')
print('inputs:')
print(x)
print('targets:')
print(y)
x.shape

inputs:
tensor([[58,  1, 47, 62, 79, 54, 71, 57],
        [58, 62, 71,  1, 65, 58, 54, 73],
        [72, 58,  1, 58, 77, 69, 71, 58],
        [ 1, 65, 62, 73, 73, 65, 58,  1]])
targets:
tensor([[ 1, 47, 62, 79, 54, 71, 57,  9],
        [62, 71,  1, 65, 58, 54, 73, 61],
        [58,  1, 58, 77, 69, 71, 58, 72],
        [65, 62, 73, 73, 65, 58,  1, 47]])


torch.Size([4, 8])